# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

href: true

title: Tutorials | HimaliWorld 
email: tutorials@himaliworld.com 
description:  Tutorials on Computer Network, Programming, Frameworks 
baseurl:  # the subpath of your site, e.g. /blog
url: "https://himaliworld.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username: avadhuta03 



environment: production


# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-162213875-1

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account

disqus: 
  shortname: avadhuta03-github-io

excerpt_separator: <!--continue-->
paginate: 9
paginate_path: "/page:num" 
permalink: /:title/


# Build settings
markdown: kramdown
theme: minima 
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
